sonar.projectKey=mariomc77_turismo-local-poc
sonar.organization=mario1098
sonar.projectName=turismo-local-poc
sonar.projectVersion=1.0
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/coverage/**,**/*.test.jsx,**/*.test.js,**/test/**,**/DataSeeder.java,frontend/src/main.jsx,frontend/src/App.jsx,frontend/src/routes/**
sonar.test.inclusions=backend/src/test/java/**/*.java,frontend/src/**/*.test.jsx,frontend/src/**/*.test.js

sonar.java.binaries=backend/target/classes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=\
backend/src/main/java/com/turismo/backend/BackendApplication.java,\
backend/src/main/java/com/turismo/backend/config/**,\
backend/src/main/java/com/turismo/backend/security/**,\
backend/src/main/java/com/turismo/backend/common/**,\
backend/src/main/java/com/turismo/backend/**/controller/**,\
backend/src/main/java/com/turismo/backend/**/entity/**,\
backend/src/main/java/com/turismo/backend/**/repository/**,\
backend/src/main/java/com/turismo/backend/**/dto/**,\
backend/src/main/java/com/turismo/backend/**/request/**,\
backend/src/main/java/com/turismo/backend/**/response/**,\
backend/src/main/java/com/turismo/backend/**/exception/**,\
frontend/src/pages/AdminPlacesPage.jsx,\
frontend/src/pages/AdminTownsPage.jsx,\
frontend/src/pages/AdminUsersPage.jsx,\
frontend/src/components/GoogleLoginButton.jsx,\
frontend/src/api/axiosConfig.js,\
frontend/src/pages/TownLoginPage.jsx
frontend/src/components/LanguageSwitcher.jsx,frontend/src/components/Navbar.jsx,frontend/src/components/PlaceCard.jsx,frontend/src/components/QRCodeCard.jsx,frontend/src/i18n/**