sonar.projectKey=mariomc77_turismo-local-poc
sonar.organization=mariomc77

sonar.projectName=turismo-local-poc
sonar.projectVersion=1.0

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/*.test.jsx,**/*.test.js,**/test/**,**/coverage/**

sonar.test.inclusions=backend/src/test/java/**/*.java,frontend/src/**/*.test.jsx,frontend/src/**/*.test.js

sonar.java.binaries=backend/target/classes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8